[package]
name = "event-query-lang"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2"
nom = "8"
nom_locate = "5"

[dependencies.serde]
version = "1"
features = ["derive"]

[dev-dependencies.insta]
version = "1.44"
features = ["yaml"]